management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
    beans:
      enabled: 'true'
    info:
      enabled: 'true'
    shutdown:
      enabled: 'true'
  server:
    address: localhost
    port: '11001'

eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:15000

cloud:
  gateway:
    default-filters:
      - DedupeReponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: 'http://localhost:12000'
          allow-credentials: true
          allowedHeaders: '*'
          allowedMethods:
            - PUT
            - GET
            - POST
            - DELETE
            - OPTIONS


jwt:
  token:
    access:
      valid:
        time: '300'
      name: jwtAccessToken
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    creator: poly
  secret:
    key: '12345678123456781234567812345678123456781234'
server:
  port: '11000'
