management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
    beans:
      enabled: 'true'
    info:
      enabled: 'true'
    shutdown:
      enabled: 'true'
  server:
    address: localhost
    port: '11001'

eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url: http://loclhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:15000

jwt:
  token:
    access:
      valid:
        time: '300'
      name: jwtAccessToken
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    creator: poly
  secret:
    key: '12345678123456781234567812345678123456781234'
server:
  port: '11000'
