management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
    beans:
      enabled: 'true'
    info:
      enabled: 'true'
    shutdown:
      enabled: true
  server:
    address: localhost
    port: '11001'

# JPA
spring:
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: 'true'
    show-sql: 'true'
    open-in-viw: 'false'
  application:
    name: USER-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:15000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '1234'
    username: closet
    url: jdbc:mariadb://192.168.2.134:3306/userDB

jwt:
  token:
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'
  redis:
    host: 192.168.2.134
    port: 6379
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: '13000'
api:
  gateway: localhost:11000