management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
    beans:
      enabled: 'true'
    info:
      enabled: 'true'
    shutdown:
      enabled: true
  server:
    address: localhost
    port: '11001'

# MongoDB Connection
spring:
  data:
    mongodb:
      host: 192.168.2.129
      port: 27017
      database: TestCollection
      username:
      password:
  application:
    name: USER-SERVICE

jwt:
  token:
    creator: poly
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12341234'
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8751/eureka
server:
  port: '11000'